### ISSUE TITLE
[Game] Pokemon Multi Move inputs gives an extra input.

### ISSUE THREAD

**Issue by GreenOtter5** [crscillitoe/RoboBananaFrontend#40]
When using the /hooj pokemon move:Left amount:4 command or the /hooj pokemon move:Right amount:4 both of these commands will output 5 of there respective commands to the emulator causing the player character to walk an extra step then was intended. Was able to test it with 1 through 5 amounts and it seems like 4 is the only one giving the extra input. Logs were check to verified I was the only person using the command at the time and the logs are on 12:36 to 12:37pm CST April 28 2024, from user greenotter24.

**Comment by DarkView** [comment]
Known issue, @ValpsZ is working on the fix. Calculations are a bit wonky. especially with turning the character taking a few extra frames. Will hopefully be fixed tomorrow.
