### ISSUE TITLE
Error | environment.dev.ts path in file replacements does not exist.

### ISSUE THREAD

**Issue by barkinunal** [crscillitoe/RoboBananaFrontend#43]
The full error log is here after running `npm install`, `ng build` and `npm run start`:

```
An unhandled exception occurred: 
The C:\Users\barki\Documents\RoboBananaFrontend\src\environments\environment.dev.ts 
path in file replacements does not exist.
```

Am I doing something wrong by running the file or do I need additional file to be able to run the app?

**Comment by ValpsZ** [comment]
I fixed this by cloning the enviroment.ts and renaming it to environment.dev.ts. Not sure if it's the right way but it compiles.

**Comment by Tiranthine** [comment]
Hay barkinunal,
the file you mentioned is indeed .gitignored - on purpose.
You can copy the `environment.prod.ts` and rename it. Depending on what you want to test, you might need to adjust some of the property values inside. But especially when you only work on the frontend itself, everything should be fine.
(Nice side effect: you should be able to receive the actual live comments made by chatters in the stream :))

**Comment by barkinunal** [comment]
Thank you for your quick response :)
